### ISSUE TITLE
unmask() does not remove the "maxlength" attribute

### ISSUE THREAD

**Issue by kefir500** [igorescobar/jQuery-Mask-Plugin#507]
Version [**1.14.2**](https://github.com/igorescobar/jQuery-Mask-Plugin/releases/tag/v1.14.2) adds the next feature:
> apply auto maxlength in case the mask doesn't have recursive pattern

However, the `unmask()` function **does not** remove the `maxlength` attribute added by this behavior, and the unmasked input length is still limited by the previously set mask pattern.

Example: [https://jsfiddle.net/t2cakzgb/3](https://jsfiddle.net/t2cakzgb/3)

The affected versions are **1.14.2** to the current (**1.14.8**).  
The temporary solution is to manually call the `removeAttr('maxlength')`.

**Comment by nunesbeto** [comment]
+1

**Comment by chirogamer** [comment]
what is this

**Comment by pedrofurtado** [comment]
@igorescobar Any news about this issue?

Because I am having the same issue. Here is my example in JSFiddle: https://jsfiddle.net/13cqy6jy/2/

Even calling *unmask()* function, the attribute "maxlength" is not removed from input tag.

Is it possible to make something like this in source code of library?

```javascript
$.fn.unmask = function() {
        clearInterval($.maskWatchers[this.selector]);
        delete $.maskWatchers[this.selector];
        return this.each(function() {
            var dataMask = $(this).data('mask');
            if (dataMask) {
                dataMask.remove().removeData('mask');
            }

            $(this).removeAttr('maxlength'); // <- Hereis the new code!
        });
    };
```

**Comment by igorescobar** [comment]
I will fix it asap, no problem.

**Comment by andraeinstein** [comment]
is this already fixed? 
Any news 'bout this issue?

**Comment by natezander** [comment]
I still see this bug in version 1.14.12

**Comment by nusendra** [comment]
is this bug still exists?

**Comment by dougjohnston** [comment]
Still seeing this bug in 1.14.13.

**Comment by nusendra** [comment]
Now i'm playing with vue, i dont use this anymore

**Comment by pedrofurtado** [comment]
@igorescobar Any news about this issue?

**Comment by vonsky104** [comment]
Guys, what @pedrofurtado said is working, just find fn.unmask function in jquery.mask.js and paste 
`$(this).removeAttr('maxlength');` just after
`  if (dataMask) {
                dataMask.remove().removeData('mask');
            }`
Thanks for that I can now mask, then unmask and mask again (I had a select with different Phone numbers from different countries and input masks needed to be different).

**Comment by pedrofurtado** [comment]
@igorescobar Any news about this issue?

**Comment by marcioJesus** [comment]
Any news?

**Comment by pedrofurtado** [comment]
Bug fixed in version "v1.14.14".

**Comment by igorescobar** [comment]
Enjoy ;)

**Comment by DylanDelobel** [comment]
Bug still exists in version `v1.14.15` and `v1.14.14`

To reproduce take the first jsfiddle and change the library version
